quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books20262026
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015

quarkus.hibernate-orm.database.generation=none

quarkus.http.port=8081
quarkus.http.host=0.0.0.0

#para puertos estaticos
#authors.url.lb=localhost:8070,localhost:8071
#quarkus.stork.authors-api.service-discovery.type=static
#quarkus.stork.authors-api.service-discovery.address-list = ${authors.url.lb}
#quarkus.stork.authors-api.load-balancer.type=round_robin

#para puertos dinamicos
quarkus.stork.authors-api.service-discovery.type=consul
quarkus.stork.authors-api.service-discovery.consul-host=${consul.host}
quarkus.stork.authors-api.service-discovery.consul-port=${consul.port}
quarkus.stork.authors-api.service-discovery.application=app-authors

#para produccion se pone tiempos mas largos ,en desarrollo se pone tiempos mas cortos
quarkus.stork.authors-api.service-discovery.refresh-period=5000


#--CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.* /
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=X-Requested-With,Content-Type,Accept,Origin,Authorization

#optional, default to the system username
quarkus.container-image.group=edlith

#optional, defaults to the application name
quarkus.container-image.name=app-books

#optional, defaults to the application version
quarkus.container-image.tag=latest

quarkus.kubernetes.env.vars.quarkus-datasource-jdbc-url=jdbc:postgresql://postgres:5432/books-db

