# docker build -f src/main/docker/Dockerfile.jvm -t app-customers .
# docker build -f src/main/docker/Dockerfile.jvm -t edlith777/app-customers .

FROM docker.io/eclipse-temurin:25.0.3_9-jre-alpine

ENV LANGUAGE='en_US:en'

RUN mkdir /app
WORKDIR /app

# Para Spring Boot, solo necesitas el JAR generado
COPY build/libs/app-customers-1.0-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]