CREATE TABLE authors (
                         id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         name VARCHAR(255),
                         CONSTRAINT pk_authors PRIMARY KEY (id)
);

INSERT INTO authors(name) VALUES ('Jorge Luis Borja');
INSERT INTO authors(name) VALUES ('Gabriel Garcia Marquez');
INSERT INTO authors(name) VALUES ('Isabel Allende');
